world_model: models/mjcf/scenes/world_scene.xml
use_viewer: True

devices:
  - name: arm_right
    type: robot
    enabled: True
    model_path: models/mjcf/robots/panda/panda_position.xml
    base_pose:
      position: [0.0, -0.4, 0.9]
      orientation: [0.5, 0.5, 0.5, 0.5]
    q0: [0.0, -0.785398, 0.0, -2.356194, 0.0, 1.570796, 0.785398, 0.04, 0.04]

  - name: arm_left
    type: robot
    enabled: True
    model_path: models/mjcf/robots/panda/panda_position.xml
    base_pose:
      position: [0.0, 0.4, 0.9]
      orientation: [0.5, -0.5,  0.5, -0.5]
    q0: [0.0, -0.785398, 0.0, -2.356194, 0.0, 1.570796, 0.785398, 0.04, 0.04]

  - name: head
    type: robot
    enabled: True
    model_path: models/mjcf/robots/pan_tilt_head/pan_tilt_position.xml
    base_pose:
      position: [0.0, 0.0, 1.13]
      orientation: [0.0, 0.0, 0.0, 1.0]
    q0: [1.57, 0.0]


objects:
  - name: table
    type: static
    model_path: models/mjcf/objects/table.xml
    pose:
      position: [0.5, 0, 0]
      orientation: [1, 0, 0, 0]